/* tslint:disable */
/* eslint-disable */
/**
 * Api Documentation
 * Api Documentation
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface ComUserMst
 */
export interface ComUserMst {
    /**
     * 
     * @type {string}
     * @memberof ComUserMst
     */
    createDt?: string;
    /**
     * 
     * @type {string}
     * @memberof ComUserMst
     */
    createUserId?: string;
    /**
     * 
     * @type {string}
     * @memberof ComUserMst
     */
    nickName: string;
    /**
     * 
     * @type {string}
     * @memberof ComUserMst
     */
    updateDt?: string;
    /**
     * 
     * @type {string}
     * @memberof ComUserMst
     */
    updateUserId?: string;
    /**
     * 
     * @type {string}
     * @memberof ComUserMst
     */
    userId: string;
    /**
     * 
     * @type {string}
     * @memberof ComUserMst
     */
    userName: string;
}


